### ISSUE TITLE
Filter results by hardware architecture

### ISSUE THREAD

**Issue by jcoleman0redhat0com** [AdiY10/SpotCalculator#1]
Feature request: allow the results to be filtered based on hardware architecture (e.g. x86_64, arm, mac).

AWS now offers x86_64- and Arm-based instances (see https://aws.amazon.com/ec2/instance-types/ for the list).  Running pre-built containers means choosing an instance type with a matching hardware architecture.  However, the current results do not distinguish hardware architecture, so results that cannot be used may be returned.  For example, the a1.* (Arm) instances are currently cheaper than x86_64 (Xeon or EPYC) instances but cannot be used for x86_64 containers.

**Comment by AdiY10** [comment]
Hi!
Thank you for creating this issue.
Input processor architecture is now possible (64-bit arm / 64-bit x86 / 64-bit mac / 32-bit), so that the results can be filtered accordingly.
See README or contact us directly for more information.
